# Generated by Django 5.2.6 on 2025-12-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
    ]
